### ISSUE TITLE
Stream stop/start creates a new hash

### ISSUE THREAD

**Issue by elv-serban** [eluv-io/elv-live-stream#2]
After an initial fix  -  https://github.com/eluv-io/elv-live-stream/commit/90fbf24f8b5b68f820ab88fdf8dac84269c4feae
The app still creates a new hash upon clicking "start"

**Comment by elv-gerald** [comment]
@elv-zenia pushed a set of changes to demo and dev prod that are working. 

I tested this on demo and prod using fox streams. After stop then start the object version stayed the same.

**Comment by elv-gerald** [comment]
This is resolved now
