### ISSUE TITLE
Streams listing table gets hung

### ISSUE THREAD

**Issue by elv-gerald** [eluv-io/elv-live-stream#21]
I noticed that the streams listing table will not show up for all the streams when one of the status calls fails or a node is down. 

Below is a screenshot of what is looks like for a user. In the screenshot there were nodes going through upgrades so some of the API calls to the relevant node would fail as expected but this would cause all the other streams not list off properly (see the status column is empty along with stream controls)

<img width="1734" alt="Screenshot 2024-04-30 at 11 01 57 PM" src="https://github.com/eluv-io/elv-live-stream/assets/79117605/d87c5642-932a-410e-a75f-07050e3020bc">

Here is a specific case I ran into on demo. It seems my udp-fox-247-tester failed on some call and the rest of the streams on the listing page did not load like the screenshot above. 
```
main.js:2 Failed to load status for undefined. TypeError: Cannot read properties of undefined (reading 'udp-fox-247-tester')
    at e.<anonymous> (main.js:2:2298230)
    at We (main.js:2:1754109)
    at ObservableObject.key (main.js:2:1753627)
    at main.js:2:2303047
    at d (main.js:2:2290794)
    at Generator.<anonymous> (main.js:2:2292137)
    at Generator.next (main.js:2:2291223)
    at Bk (main.js:2:2289882)
    at o (main.js:2:2290086)
```

**Comment by elv-zenia** [comment]
Relates to https://github.com/eluv-io/elv-live-stream/commit/51971d2bc52bb987aecae45875bd5d917d771f65 and https://github.com/eluv-io/elv-live-stream/commit/943ed39b2493a55f51a6304df3e600f96abf9465
Deployed to demo
This should fix the case where multiple stream statuses fail to display if one fails. I still want to investigate why certain active streams have no edge write token metadata

**Comment by elv-gerald** [comment]
Closing for now. I would routinely see this on prod for fox streams. Ive been testing on prod dev using the fox tenancy and I have ran into no issues. If I run into another case Ill try to collect as much info and open a new ticket.
