### ISSUE TITLE
Probe button on creation page bug

### ISSUE THREAD

**Issue by elv-gerald** [eluv-io/elv-live-stream#22]
I noticed the probe button on the creation page has no guards. I can click on the probe button with all the other fields empty. Can we disable the probe button unless the user has entered the required fields (right now I can click on probe without any of these). 

At minimum what is required is:
- url
- name
- library

**Comment by elv-zenia** [comment]
Relates to https://github.com/eluv-io/elv-live-stream/commit/079a29d5f4f519a9a5b94fa5adf20c02861bebd0
Pushed to demo

**Comment by elv-gerald** [comment]
Verified probe button can only be interacted with when the minimum requirements are met.
