### ISSUE TITLE
Default stream retention to 6 hours

### ISSUE THREAD

**Issue by elv-gerald** [eluv-io/elv-live-stream#23]
Right now on creation we set the stream retention to 1 hour. This was mainly to avoid a large metadata slowness. This issue has been mitigated and we are safe to use a 6 hour retention period by default on newly created streams.

**Comment by elv-zenia** [comment]
Relates to https://github.com/eluv-io/elv-live-stream/commit/0e00eae3ec460dedb2bf519395ec22eceb2444bd
Pushed to demo

**Comment by elv-gerald** [comment]
Verified new Streams are getting 6 hours as the default retention period
