### ISSUE TITLE
Add 128 Kbps bitrate option for audio tracks

### ISSUE THREAD

**Issue by elv-gerald** [eluv-io/elv-live-stream#24]
I noticed we were also missing 128 Kbps bitrate for audio tracks. 128 Kbps is also a very common Bitrate used for audio. 

<img width="227" alt="image" src="https://github.com/eluv-io/elv-live-stream/assets/79117605/dbc2cb18-5849-42ba-91fe-01612f09ee92">

**Comment by elv-zenia** [comment]
Relates to https://github.com/eluv-io/elv-live-stream/commit/108f7430d0dc7e54a48251bba65ceb940d0425a2
Pushed to demo

**Comment by elv-gerald** [comment]
New option is now present
