### ISSUE TITLE
Prevent user from saving adding audio to playout without a label

### ISSUE THREAD

**Issue by elv-gerald** [eluv-io/elv-live-stream#25]
On demo we noticed there is no guard that prevents the user from enabling play out of audio while leaving the label empty. I see no issues after saving but this might have negative consequences on some players.

<img width="1410" alt="image" src="https://github.com/eluv-io/elv-live-stream/assets/79117605/e81ab80d-f683-481e-a826-46dc80a0fece">

**Comment by elv-zenia** [comment]
Relates to https://github.com/eluv-io/elv-live-stream/commit/eff6fd242a411dc354b48f71fa63932bcb6654df
Deployed to demo

**Comment by elv-gerald** [comment]
Verified I cannot add playout with empty labels
