### ISSUE TITLE
Add directions to probe dialogue on stream creation page

### ISSUE THREAD

**Issue by elv-gerald** [eluv-io/elv-live-stream#26]
Can we add the directions to also uinstruct users to send their stream to the url when they probe their stream on the stream creation page?  

Right now it does not show any of these instructions on the dialogue and it will be confusing to new user. We can also keep the text that a new object will be created. 
<img width="730" alt="Screenshot 2024-05-06 at 4 49 36 PM" src="https://github.com/eluv-io/elv-live-stream/assets/79117605/eb0f6071-e3e3-4f3e-b843-4045cdd449f2">

**Comment by elv-zenia** [comment]
Relates to https://github.com/eluv-io/elv-live-stream/commit/7a7b12a65d6aae763071008d25f36d3a7fdcde2c
Deployed to demo

**Comment by elv-gerald** [comment]
verified that instructions are showing up now
