### ISSUE TITLE
Probe data is duplicated in object metadata

### ISSUE THREAD

**Issue by elv-gerald** [eluv-io/elv-live-stream#27]
I set up a new stream `iq__2o6EEW51VTpw37qUKerrrBDbtdHa` (this is on paladin)

I did the following 
 - probe on creation page
 - remove last audio from only from playout
 - set up public access drm
 - re-labled all the streams

In the object metadata I can see my probe data got duplicated after submitting the creation. 

You can see on version 4 the probe gets added and on version 6 the probe data gets added again.

**Comment by elv-gerald** [comment]
I quickly tested it looks like its related to probing on the creation page. I created a new object that only probed on the creation page and I modified nothing else. This process reproduced the issue on object `iq__2kEVzcGUHm2ULvYv8HTqbX7bcrbm`.

**Comment by elv-zenia** [comment]
Relates to https://github.com/eluv-io/elv-live-stream/commit/2615b03666710d77e0b021e419694d00af0db29e
Deployed to demo

**Comment by elv-gerald** [comment]
resolved
