### ISSUE TITLE
Remove audios from ladder when user opts to not record them

### ISSUE THREAD

**Issue by elv-gerald** [eluv-io/elv-live-stream#29]
We noticed that in multiaudio streams when the user opts to not record certain audios in a live stream the audios were still present in the ladder (even though the label was null). This was resulting in audios still being recorded when I looked at LRO status. 

In the case to not record we simply should not include the audios in the ladder. Below is an example of what to expect. 

Using these settings
<img width="1418" alt="image" src="https://github.com/eluv-io/elv-live-stream/assets/79117605/6518df23-dbf9-4889-93a9-92ac36938b1d">

The meta should look like the following 
```json
    "recording_config": {
      "recording_params": {
        "description": "Ingest stream udp://host-76-74-28-234.contentfabric.io:11042",
        "ladder_specs": [
           ...
           // Only the single audio should exist here
          {
            "bit_rate": 384000,
            "channels": 6,
            "codecs": "mp4a.40.2",
            "media_type": 2,
            "representation": "audioaudio_aac@384000",
            "stream_index": 0,
            "stream_label": "Audio 0",
            "stream_name": "audio_0"
          }
        ],
        ...
        "xc_params": {
          "audio_bitrate": 384000,
          // This stays the same
          "audio_index": [
            0,
            1,
            0,
            0,
            0,
            0,
            0,
            0
          ],
         ...
          // update this to the number of audios being recorded (in this case 1)
          "n_audio": 1,
        ...
        }
      }
    }
  },
```

**Comment by elv-zenia** [comment]
Relates to https://github.com/eluv-io/elv-live-stream/commit/0105edc49427dd770bc61f244effd43c66b3c245
Deployed to demo

**Comment by elv-gerald** [comment]
FYI @elv-serban I found a small backend issue. If we disable all audio recording the streams will refuse to start.

**Comment by elv-gerald** [comment]
Verified. Using a 5 audio stream I tested the following 
- Record and enable live play out for all audios
- Record only 1 and enable lvie play out only 1 audio
- Record all audios but only enable 3 for live playout

I verified the correct actions were being taken by inspecting the parts being created and by performing live to vod on the cases above.
