### ISSUE TITLE
Sanitize srt passphrase from showing up on the streams listing table

### ISSUE THREAD

**Issue by elv-gerald** [eluv-io/elv-live-stream#30]
We managed to get passphrase SRT streaming working and overlooked that the passphrase will show up in the stream listing table. The passphrase argument will need to be sanitized on this view. 

<img width="2064" alt="image" src="https://github.com/eluv-io/elv-live-stream/assets/79117605/7599e33a-081a-486f-9506-5cb27ad29337">

**Comment by elv-zenia** [comment]
Relates to https://github.com/eluv-io/elv-live-stream/commit/c8ce752eea288ae3f292f17a8cb57961098daa46
Deployed to demo

**Comment by elv-gerald** [comment]
Verified. I no longer see the SRT arguments printed out on the stream listing table.
