### ISSUE TITLE
Recording periods that are longer than TTL show as avaiable

### ISSUE THREAD

**Issue by elv-gerald** [eluv-io/elv-live-stream#32]
This might be back end related but I am creating this ticket to at least track the issue.

On the manager I notice there are recording periods showing up as available even though the stream periods are passed the TTL length.

For example in the image below the stream has a TTL set to 1 hour but the long periods still show available. This is best able to been seen in the fox tenancy. All the stream there have a TTL of 1 hour. 
<img width="2079" alt="image" src="https://github.com/eluv-io/elv-live-stream/assets/79117605/8d2ea460-093e-4e10-a4a8-b4151baf0978">

**Comment by elv-zenia** [comment]
It looks like the metadata for edge write token recordings changed. I updated the app to use
- RECORDING/sources/trimmed instead of RECORDING/sources/video_trimmed
- RECORDING/sources/video/parts instead of RECORDING/sources/video

Relates to https://github.com/eluv-io/elv-live-stream/commit/0ccb64d327e142c8c71cdff865739f402fe62555
Deployed to demo and prod-dev.

**Comment by elv-gerald** [comment]
Its working better now but I see one issue, the case for "Partially Available" is not working. 

In the example stream below, it has a TTL of 1 hour and I was expecting to see the current running period of 12 hours to show as partially available
<img width="1658" alt="image" src="https://github.com/eluv-io/elv-live-stream/assets/79117605/29b2479d-b10f-4138-a688-372ba564e8a5">

**Comment by elv-zenia** [comment]
Relates to https://github.com/eluv-io/elv-live-stream/commit/f28f9e7b3271aa7a9f5c20edd721391730a5920f
Deployed to demo and prod-dev.

**Comment by elv-gerald** [comment]
Verified that the listing is looking correct now with regard to available, partially available, and not available.
