### ISSUE TITLE
Watermark gets removed from meta when modifying audio settings

### ISSUE THREAD

**Issue by elv-gerald** [eluv-io/elv-live-stream#34]
Steps for reproductions
1. Create new stream
2. Add watermark
3. Verify watermark is present in meta
4. Modify audio params (I renamed a label)
5. Watermark stanza is removed from meta

Here is a diff of changes the manager did to my test stream
<img width="1836" alt="image" src="https://github.com/eluv-io/elv-live-stream/assets/79117605/31be2213-7557-4d89-8e91-9b124c864d98">

**Comment by elv-zenia** [comment]
Deployed a fix to demo and prod-dev.

**Comment by elv-zenia** [comment]
Sorry about that. I changed the build when I deployed the DRM changes. I just brought everything together and re-deployed to demo.

**Comment by elv-gerald** [comment]
AHH that makes sense. Will try again.

**Comment by elv-gerald** [comment]
Verified. I tried the same steps to reproduce the issue and the audio changes do not affect the watermark anymore.

Checked both playout and diff to ensure the watermark did not get wiped
