### ISSUE TITLE
Support for DVR configuration 

### ISSUE THREAD

**Issue by elv-gerald** [eluv-io/elv-live-stream#52]
We will need to have a brain storm session on how we want to add support for DVR.  This feature is already deployed to demo and I have been manually configuring streams to test this.

For now this ticket can serve as a general overview of DVR based on my testing

PR for qfab: https://github.com/qluvio/content-fabric/pull/2859#issue-2458103156

DVR is controlled using the following parameters in the "playout_config" of a stream config. Here are notes from my testing
- dvr_enabled: true or false (if not present, false is implied) 
- dvr_start_time: ISO 8601 / RFC 3339 format of when the DVR start time (optional)
- dvr_max_duration: Amount of time in seconds the DVR sliding window will be open for (optional, this is bound by ttl. If longer than ttl  nothing bad will happen, the sliding window will be controlled by ttl). Leaving this omitted or setting it to "0" means max dvr duration.  

Examples 
#### enable dvr on a stream with max duration 
```json
"playout_config": {
          "dvr_enabled": true,
          ...
```

#### enable dvr, start at 19:55 UTC time with max duration 
```json
"playout_config": {
          "dvr_enabled": true,
          "dvr_start_time": "2024-08-14T19:55:00Z",
          "dvr_max_duration": 0,
          ...
```

#### enable dvr, start at 13:30 PDT time and set the max duration to 1 hour
```json
"playout_config": {
          "dvr_enabled": true,
          "dvr_start_time": "2024-08-30T13:30:00-07:00",
          "dvr_max_duration": 3600
          ...
```

#### enable dvr, start at 13:30 PDT time and max duration of 30 min
```json
"playout_config": {
          "dvr_enabled": true,
          "dvr_max_duration": 1800
          ...
```

### Additional notes
- With DVR enabled to fetch playlist with dvr simply add `dvr=1` argument to playlist request. Same with embed URL.
- You can still fetch the non dvr playlist or embed url from a dvr enabled stream, just do not include `dvr=1` in the requests. 

#### Start time notes
- What happens if you request playout before start time? The playlist request will be empty, the embed player will also error out. Playout will work AFTER the start time. 
- dvr_start_time **will only work** on playlist/embed urls with `dvr=1`, it will be ignored if you omit the argument from the urls.

**Comment by elv-serban** [comment]
For the Live Stream App h

`DVR`

- Enabled   - checkbox
  - Enable DVR playout - user can seek back in the live stream
- Start Time.  - Date Time
  - Users can only seek back to this point in time. Useful for event streams.
- Max Duration. - Time Duration (not sure how best to specify - maybe just in 'minutes')
  - Users can only seek back only this many minutes.  Useful for 24/7 streams and long events.

**Comment by elv-gerald** [comment]
I found a bug. 

`dvr_start_time` is optional. When I configured my stream to not include a start time I got an error
```
index-DOjALbTI.js:200 Unable to configure watermark TypeError: Cannot read properties of null (reading 'toISOString')
    at fEe.<anonymous> (index-DOjALbTI.js:254:162588)
    at Generator.next (<anonymous>)
    at gO (index-DOjALbTI.js:42:6173)
    at <unnamed flow> - runid: 830 - yield 3 (index-DOjALbTI.js:42:5992)
    at v (index-DOjALbTI.js:42:22998)
```

Here is how my form looked
![image](https://github.com/user-attachments/assets/9c748df3-3bc3-4715-8d75-d38a4b729bbe)

**Comment by elv-zenia** [comment]
Fixed the above bug, plus the following:
- Make form subsections more discernible on the edit stream tab views
![image](https://github.com/user-attachments/assets/811baccf-eed5-4b9c-8913-fde2dcefbc16)
- Set connection timeout dropdown option to "Select connection timeout" when the current value doesn't match current options.

Updated prod-dev.

**Comment by elv-gerald** [comment]
I am testing on demo and I notice on new stream I create and configure the `reconnect_timeout` is not being set in the config meta. I see it defaults to 1 hour in the form but it is not present in the config. 

The path  I am looking for the value resides in `live_recording.recording_config.recording_params.reconnect_timeout` 
<img width="571" alt="image" src="https://github.com/user-attachments/assets/359f9204-0131-44b4-8c14-e531d4fd2ae4">

I also notice in the timeout drop downs I can select "Select Time Duration" as a value
<img width="855" alt="image" src="https://github.com/user-attachments/assets/f3185378-b89e-4289-ac08-df07752e72d7">

**Comment by elv-zenia** [comment]
Pushed a [fix](https://github.com/eluv-io/elv-live-stream/commit/a4dc69003f854aa87dc5ffdcaf7fa92af380a0a4) and updated demo and prod-dev.

**Comment by elv-gerald** [comment]
Today we also agreed to explicitly set `reconnect_timeout` and `connection_timeout` to 10 minutes (600 seconds) in the metadata for all created streams.

**Comment by elv-zenia** [comment]
Deployed to prod.
