### ISSUE TITLE
Copy to VoD - support for selecting library

### ISSUE THREAD

**Issue by elv-serban** [eluv-io/elv-live-stream#65]
Since commonly streams are in a Live Streams library and VoD objects in Title Mezzanines, allow the user to also select the library where the content will go.

Preselect the library where the live stream is located (which would give the same behavior we have now, with a single click)

Also for the suggested name of the VOD object use this template:
`VOD - 2024-10-10 - {display_title_or_title_or_name}`

Where the date is the start date of the live stream

<img width="910" alt="image" src="https://github.com/user-attachments/assets/767b0204-1144-4a42-987e-75191c448250">

**Comment by elv-zenia** [comment]
Deployed to demo and prod-dev.

**Comment by elv-zenia** [comment]
Deployed to prod.
