### ISSUE TITLE
Only allow DVR editing when the stream is stopped

### ISSUE THREAD

**Issue by elv-gerald** [eluv-io/elv-live-stream#67]
Today we noticed we can edit DVR settings while a stream is in a "running" status. Can we enforce that these settings can only be edited while "stopped"?

**Comment by elv-zenia** [comment]
I added a change to disable the DVR section when status IS NOT `stopped`. Deployed to demo and prod-dev.

**Comment by elv-gerald** [comment]
ahh I forgot to add, can we also allow editing when "Inactive"?
<img width="1085" alt="image" src="https://github.com/user-attachments/assets/4956d59c-63e0-4ffa-9e56-086dad655c90">

**Comment by elv-zenia** [comment]
Fixed by https://github.com/eluv-io/elv-live-stream/pull/68/commits/4dda6e27f4f036dbd30fae2a79cb3e33290f1101. Deployed to demo.
